language: node_js
node_js:
  - 14.17.2

services:
  - docker

script:
  - docker-compose up
  - docker cp ~/node/keys bettery_app:~/app/

deploy:
  - provider: codedeploy
    application: Bettery_dev
    access_key_id: $AWSAccessKeyId
    secret_access_key: $AWSSecretKey
    region: ap-southeast-1b
    deployment_group: launch-wizard-2
    on:
      branch: validate-tokens

