version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app
file_exists_behavior: OVERWRITE

hooks:
  BeforeInstall:
    - location: build_scripts/beforeInstall.sh
  AfterInstall:
    - location: build_scripts/start.sh
