image: node:14.17.2

options: 
  docker: true

pipelines:
  branches:
    validate-tockens:
      - step:
          script:
            - apt update
            - apt install docker.io
            - docker-compose up