image: node:14.17.2

options: 
  docker: true

pipelines:
  branches:
    validate-tockens:
      - step:
          script:
            # - apt-get update # required to install zip
            # - apt-get install -y zip # required for packaging up the application
            # - pip install boto3==1.3.0 # required for codedeploy_deploy.py
            # - zip -r /tmp/artifact.zip * # package up the application for deployment
            # - python codedeploy_deploy.py # run the deployment script
            - apt-get update
            - sudo apt-get install docker-ce docker-ce-cli containerd.io
            - docker-compose up