image: docker/compose:1.25.4

pipelines:
  branches:
    validate-tockens:

      - step:
          name: Build
          script:
          services:
            - docker
          script:           
            - docker build -t bettery_img . 
            - npx jest

      # - step:
      #     name: Upload to S3
      #     script:
      #       - pipe: atlassian/aws-code-deploy:0.2.6
      #         variables:
      #           AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      #           AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      #           AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      #           COMMAND: 'upload'
      #           APPLICATION_NAME: ${APPLICATION_NAME}
      #           S3_BUCKET: codedeploy-bucket-bettery-dev
      #           ZIP_FILE: 'myapp.zip'

      # - step:
      #     name: Deploy with CodeDeploy
      #     script:
      #       - pipe: atlassian/aws-code-deploy:0.2.10
      #         variables:
      #           AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
      #           AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      #           AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      #           COMMAND: 'deploy'
      #           APPLICATION_NAME: $APPLICATION_NAME
      #           ZIP_FILE: 'myapp.zip'
      #           DEPLOYMENT_GROUP: $DEPLOYMENT_GROUP_NAME
      #           FILE_EXISTS_BEHAVIOR: 'OVERWRITE'
      #           WAIT: 'true'

      # - step:
          # services:
          #   - docker
          # caches:
          #   - docker
          # script:           
          #   - docker-compose up
          #   - docker cp ~/node/keys bettery_app:~/app/        