image: node:14.17.2

options: 
  docker: true

pipelines:
  branches:
    validate-tockens:
      - step:
          script:
            - docker-compose -v
            - docker-compose up
          

definitions:
    services:
        docker:
            image: docker/compose:1.25.4