image: docker/compose:1.25.4

pipelines:
  branches:
    validate-tockens:
      - step:
        services:
          - docker
        script:
          - npx jest
          - docker-compose up
          - docker cp ~/node/keys bettery_app:~/app/
        
