image: docker/compose:1.25.4

pipelines:
  branches:
    validate-tockens:

      - step:
          name: Build
          image: node:14.17.2
          script:
          services:
            - docker
          script:           
            - npm install
            - npx jest
            - docker build -t bettery_img . 
          artifacts:
            - build/**

      # - step:
      #     name: Upload to S3
      #     script:
      #       - pipe: atlassian/aws-s3-deploy:0.3.2
      #         variables:
      #           AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      #           AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      #           AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      #           COMMAND: 'upload'
      #           APPLICATION_NAME: ${APPLICATION_NAME}
      #           S3_BUCKET: codedeploy-bucket-bettery-dev
      #           LOCAL_PATH: "build"

      - step:
          name: Deploy with CodeDeploy
          script:
            - pipe: atlassian/aws-code-deploy:0.2.10
              variables:
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                COMMAND: 'deploy'
                APPLICATION_NAME: $APPLICATION_NAME
                DEPLOYMENT_GROUP: $DEPLOYMENT_GROUP_NAME
                FILE_EXISTS_BEHAVIOR: 'OVERWRITE'
                WAIT: 'true'

      # - step:
          # services:
          #   - docker
          # caches:
          #   - docker
          # script:           
          #   - docker-compose up
          #   - docker cp ~/node/keys bettery_app:~/app/        